proxy

diff --git a/zsh/.config/zsh/zsh-functions b/zsh/.config/zsh/zsh-functions
--- a/zsh/.config/zsh/zsh-functions
+++ b/zsh/.config/zsh/zsh-functions
@@ -24,14 +24,51 @@ function mach_java_mode() {
     [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
 }
 
+# function proxy() {
+#   export http_proxy=http://127.0.0.1:41091
+#   export https_proxy=$http_proxy
+#   export socks5_proxy="socks5://127.0.0.1:1090"
+# }
+#
+# function unproxy() {
+#   unset http_proxy
+#   unset https_proxy
+#   echo "HTTP Proxy off"
+# }
+
 function proxy() {
-  export http_proxy=http://127.0.0.1:41091
-  export https_proxy=$http_proxy
-  export socks5_proxy="socks5://127.0.0.1:1090"
+    export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"
+
+    if (( $# > 0 )); then
+        valid=$(echo $@ | sed -n 's/\([0-9]\{1,3\}.\?\)\{4\}:\([0-9]\+\)/&/p')
+        if [[ $valid != $@ ]]; then
+            >&2 echo "Invalid address"
+            return 1
+        fi
+        local proxy=$1
+        export http_proxy="$proxy" \
+               https_proxy=$proxy \
+               ftp_proxy=$proxy \
+               rsync_proxy=$proxy
+        echo "Proxy environment variable set."
+        return 0
+    fi
+
+    echo -n "server: "; read server
+    echo -n "port: "; read port
+    local proxy=$pre$server:$port
+    export http_proxy="$proxy" \
+           https_proxy=$proxy \
+           ftp_proxy=$proxy \
+           rsync_proxy=$proxy \
+           HTTP_PROXY=$proxy \
+           HTTPS_PROXY=$proxy \
+           FTP_PROXY=$proxy \
+           RSYNC_PROXY=$proxy
 }
 
-function unproxy() {
-  unset http_proxy
-  unset https_proxy
-  echo "HTTP Proxy off"
+function unproxy(){
+    unset http_proxy https_proxy ftp_proxy rsync_proxy \
+          HTTP_PROXY HTTPS_PROXY FTP_PROXY RSYNC_PROXY
+    echo -e "Proxy environment variable removed."
 }
